-- VIEWS

-- Creates a view that shows the total number of followers for each artist:
CREATE VIEW ARTIST_FOLLOWER_COUNT AS
SELECT A.ARTIST_NAME, COUNT(F.FOLLOWER_ID) AS FOLLOWER_COUNT
FROM ARTISTS A 
LEFT JOIN FOLLOWERS F ON A.ARTIST_ID = F.ARTIST_ID
GROUP BY A.ARTIST_NAME;